#pragma once

typedef enum {
  DMX_AUDIO_COMMAND_NOP = 0x00,
  DMX_AUDIO_COMMAND_STOP_ALL = 0x01,
  DMX_AUDIO_COMMAND_PLAY_ONCE_POLY = 0x02,
  DMX_AUDIO_COMMAND_PLAY_LOOP_POLY = 0x03,
  DMX_AUDIO_COMMAND_PLAY_ONCE_MONO = 0x04,
  DMX_AUDIO_COMMAND_PLAY_LOOP_MONO = 0x05,
  DMX_AUDIO_COMMAND_PLAY_ONCE_POLY_LOCKED = 0x06,
  DMX_AUDIO_COMMAND_PLAY_LOOP_POLY_LOCKED = 0x07,
  DMX_AUDIO_COMMAND_STOP = 0x08,
  DMX_AUDIO_COMMAND_PAUSE = 0x09,
  DMX_AUDIO_COMMAND_RESUME = 0x0A,
  DMX_AUDIO_COMMAND_TRACK_VOLUME = 0x0B,
  DMX_AUDIO_COMMAND_MASTER_VOLUME = 0x0C,
  NUM_DMX_AUDIO_COMMANDS
} dmxAudioCommands_t;
